-- Frontline security hardening: audit logs + storage policies
-- Run this in Supabase SQL Editor.

begin;

-- 1) Admin audit trail table
create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  action text not null,
  entity_type text not null,
  entity_id text null,
  actor_user_id uuid null,
  actor_email text null,
  details jsonb not null default '{}'::jsonb
);

create index if not exists admin_audit_logs_created_idx
  on public.admin_audit_logs (created_at desc);

create index if not exists admin_audit_logs_actor_idx
  on public.admin_audit_logs (actor_user_id, created_at desc);

alter table public.admin_audit_logs enable row level security;

drop policy if exists admin_audit_insert_staff on public.admin_audit_logs;
drop policy if exists admin_audit_read_admin_manager on public.admin_audit_logs;

create policy admin_audit_insert_staff
on public.admin_audit_logs
for insert
to authenticated
with check (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'manager', 'staff')
);

create policy admin_audit_read_admin_manager
on public.admin_audit_logs
for select
to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'manager')
);

-- 2) Ensure media buckets exist
insert into storage.buckets (id, name, public)
values ('product-photos', 'product-photos', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('offer-photos', 'offer-photos', true)
on conflict (id) do nothing;

-- 3) Tighten storage object policies for known media buckets
-- Buckets used by current code: offer-photos, offers, product-photos, product-photo

drop policy if exists media_public_read on storage.objects;
drop policy if exists media_staff_insert on storage.objects;
drop policy if exists media_staff_update on storage.objects;
drop policy if exists media_admin_manager_delete on storage.objects;

create policy media_public_read
on storage.objects
for select
to public
using (bucket_id in ('offer-photos', 'offers', 'product-photos', 'product-photo'));

create policy media_staff_insert
on storage.objects
for insert
to authenticated
with check (
  bucket_id in ('offer-photos', 'offers', 'product-photos', 'product-photo')
  and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'manager', 'staff')
);

create policy media_staff_update
on storage.objects
for update
to authenticated
using (
  bucket_id in ('offer-photos', 'offers', 'product-photos', 'product-photo')
  and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'manager', 'staff')
)
with check (
  bucket_id in ('offer-photos', 'offers', 'product-photos', 'product-photo')
  and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'manager', 'staff')
);

create policy media_admin_manager_delete
on storage.objects
for delete
to authenticated
using (
  bucket_id in ('offer-photos', 'offers', 'product-photos', 'product-photo')
  and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'manager')
);

commit;
